name: 001-TEST-VERSION

on: 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Find and Build APK
        run: |
          # 1. 自动寻找项目中的 gradlew 文件
          GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
          
          if [ -z "$GRADLEW_PATH" ]; then
            echo "❌ 错误：在整个项目中都找不到 gradlew 文件！"
            exit 1
          fi
          
          echo "✅ 找到钥匙在：$GRADLEW_PATH"
          
          # 2. 赋予执行权限
          chmod +x "$GRADLEW_PATH"
          
          # 3. 进入钥匙所在的文件夹并开始打包
          BASE_DIR=$(dirname "$GRADLEW_PATH")
          cd "$BASE_DIR"
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-BeeCount-APK
          # 自动搜寻生成的所有 apk 文件并上传
          path: "**/*.apk"
