name: ✨ 功能请求 / Feature Request
description: 为 BeeCount 提出新功能或改进建议 / Suggest new features or improvements for BeeCount
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您的建议！我们欢迎所有改进 BeeCount 的想法。
        Thank you for your suggestion! We welcome all ideas to improve BeeCount.

  - type: checkboxes
    id: preflight
    attributes:
      label: 提交前确认 / Pre-submission Checklist
      description: 请确认以下事项 / Please confirm the following
      options:
        - label: 我已查阅 [官方文档](https://beecount-website.pages.dev/docs/intro)，确认该功能尚未实现 / I have checked the [official docs](https://beecount-website.pages.dev/docs/intro) and confirmed this feature doesn't exist
          required: true
        - label: 我已在 [GitHub Issues](https://github.com/TNT-Likely/BeeCount/issues) 搜索过，没有找到相同的功能请求 / I have searched [GitHub Issues](https://github.com/TNT-Likely/BeeCount/issues) and found no similar request
          required: true
        - label: 本次请求只包含一个独立功能，不涉及多个不相关的模块 / This request contains only ONE independent feature, not multiple unrelated modules
          required: true

  - type: textarea
    id: problem
    attributes:
      label: 问题描述 / Problem Description
      description: 这个功能要解决什么问题？ / What problem does this feature solve?
      placeholder: 当我想要...的时候，我发现... / When I try to... I find that...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 期望的解决方案 / Desired Solution
      description: 您希望如何实现这个功能？ / How would you like this feature to work?
      placeholder: 我希望能够... / I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案 / Alternative Solutions
      description: 您考虑过哪些替代方案？ / What alternative solutions have you considered?
      placeholder: 也可以... / Alternatively, we could...

  - type: textarea
    id: examples
    attributes:
      label: 参考示例 / Reference Examples
      description: 有其他应用实现了类似功能吗？ / Have any other apps implemented similar features?
      placeholder: 比如某某应用的...功能 / For example, the... feature in... app

  - type: dropdown
    id: priority
    attributes:
      label: 优先级 / Priority
      description: 这个功能对您有多重要？ / How important is this feature to you?
      options:
        - 可有可无 / Nice to have
        - 有用但不紧急 / Useful
        - 很重要 / Important
        - 非常关键 / Critical
    validations:
      required: true

  - type: checkboxes
    id: willingness
    attributes:
      label: 贡献意愿 / Contribution Willingness
      description: 您愿意帮助实现这个功能吗？ / Would you like to help implement this feature?
      options:
        - label: 我愿意提交 PR 实现此功能 / I'm willing to submit a PR to implement this feature
        - label: 我可以帮助测试此功能 / I can help test this feature
        - label: 我可以提供更详细的需求说明 / I can provide more detailed requirements

  - type: textarea
    id: additional
    attributes:
      label: 补充信息 / Additional Information
      description: 还有其他需要补充的信息吗？ / Any other information you'd like to add?
